version: 2.1

orbs:
  node: circleci/node@5.2

workflows:
  sample:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm 
            environment:
            NODE_OPTIONS: "--testTimeout=60000"
